language: java

sudo: false   # Linux OS: run in container

matrix:
  include:
    # Headless Linux
    - os: linux
      dist: trusty
      jdk: openjdk11
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

addons:
  apt:
    packages:
      - openjdk-11-jdk

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == osx ]]; then brew update; brew cask reinstall caskroom/versions/java8; fi

script:
  - mvn test-compile test

before_cache:
  - rm -f  $HOME/.m2/repository

after_success:
   - bash <(curl -s https://codecov.io/bash) -t 7847e00f-65e7-423e-8f2c-636d8614aa58

cache:
  directories:
    - $HOME/.m2/repository
